### PR TITLE
fix(fetch): fix memory leak when passing `keepAlive`

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
See @marwan38's https://github.com/remix-run/web-std-io/pull/24 & @donavon's https://github.com/remix-run/web-std-io/pull/29

> This is a direct copy of https://github.com/node-fetch/node-fetch/pull/1474.
> 
> We're having memory leak issues as we're using a http agent with keepAlive options with the fetch used on the remix server.

CC/ @alanshaw @Gozala

---

#77 needs to be merged first

### CODE REVIEW

**Review by Gozala — APPROVED** [review]

**Comment by Gozala** [comment]
@MichaelDeBoey I'v attempted to resolve merge conflicts and reviewed changes. Have not merged it since PR is marked as a draft. If it's done feel free to merge.

**Comment by MichaelDeBoey** [comment]
@Gozala I don't have permissions to merge this branch, so you will need to do it
If you wish to add more maintainers to this package, I know @jacob-ebey and I would be happy to help out

**Comment by Gozala** [comment]
> @Gozala I don't have permissions to merge this branch, so you will need to do it

I have invited to the contributors team earlier today, once you accept the invite you should be able to merge.

> If you wish to add more maintainers to this package, I know @jacob-ebey and I would be happy to help out

Inviting @jacob-ebey to the team as well

**Comment by MichaelDeBoey** [comment]
> I have invited to the contributors team earlier today, once you accept the invite you should be able to merge.

Didn't see that yet 🙈
Accepted now 😉

> Inviting @jacob-ebey to the team as well

Thanks 🙏

**Pull request merged**
